@BASE_URL = http://localhost:5000

# @name Create a new task
POST {{BASE_URL}}/task
Content-Type: application/json

{
    "title": "Estudar HTML, CSS e JS",
    "description": "Estudar os cenários das tags em HTML, CSS e JS",
    "statusId": 1,
    "priorityId": 2,
    "categoryId": 1
}

###
GET {{BASE_URL}}/tasks